"""Adicionado tabela role

Revision ID: d4fa8d8f5406
Revises: d7b9641a72ad
Create Date: 2026-07-15 09:16:59.162819

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d4fa8d8f5406"
down_revision = "d7b9641a72ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    role_table = sa.table(
        "role", sa.column("id", sa.Integer), sa.column("name", sa.String)
    )
    op.bulk_insert(
        role_table,
        [
            {"id": 1, "name": "admin"},
            {"id": 2, "name": "user"},
        ],
    )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.String(length=120), nullable=False)
        )
        batch_op.add_column(sa.Column("role_id", sa.Integer(), nullable=True))
        batch_op.alter_column("active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.create_foreign_key("fk_user_role_id_role", "role", ["role_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_role_id_role", type_="foreignkey")
        batch_op.alter_column("active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.drop_column("role_id")
        batch_op.drop_column("password")

    op.drop_table("role")
    # ### end Alembic commands ###
